<?php

namespace App\Services\PageBuilder\Block;

use App\Data\PageBuilder\Block\ComplectationsTable\ComplectationsTableData;
use Spatie\LaravelData\Data;

class ComplectationsTableBlock
{
    public function viewData(): ?Data
    {
        return ComplectationsTableData::from([
            'title' => 'Комплектации и цены TENET Т4',

            'filter_keys' => [
                'engine_label',
                'transmission',
                // 'drive',
                // 'year',
                // 'seat_label',
            ],

            'complectations' => [
                [
                    'id' => 8555,
                    'name' => 'Prime',
                    'full_name' => 'Prime/1.5 л. (147 л.с.)/Турбо Бензин/AMT7/Полный/2025/4 мест',
                    'year' => '2025',
                    'codes' => ['Prime 1.5T 4WD'],
                    'prices' => [
                        'price' => 2550000,
                        'price_min' => 1720000,
                        'price_text' => 'Цена по запросу',
                        'price_text_short' => 'По запросу',
                        'show_price' => 1,
                        'price_discount_max' => 830000,
                        'price_discount_credit' => 250000,
                        'price_discount_trade_in' => 150000,
                        'price_discount_direct' => 0,
                    ],
                    'cars_count' => 11,
                    'seats' => 4,
                    'isImport' => false,
                    'transmission_type' => '',
                    'engine_url' => 'turbirovannyj',
                    'engine_volume' => '1.5',
                    'transmission' => 'Робот (AMT7)',
                    'engine_power' => '147',
                    'engine_type' => 'Турбо Бензин',
                    'drive' => 'Полный',
                    'transmission_short' => 'AMT7',
                    'url' => '#',
                    'engine_label' => '1.5 (147 л.с.) Турбо Бензин',
                    'seat_label' => '4 места',
                ],
                [
                    'id' => 8553,
                    'name' => 'Active',
                    'full_name' => 'Active/1.5 л. (147 л.с.)/Турбо Бензин/AMT7/Полный/2025/4 мест',
                    'year' => '2025',
                    'codes' => ['Active 1.5T 4WD'],
                    'prices' => [
                        'price' => 2390000,
                        'price_min' => 1592000,
                        'price_text' => 'Цена по запросу',
                        'price_text_short' => 'По запросу',
                        'show_price' => 1,
                        'price_discount_max' => 798000,
                        'price_discount_credit' => 250000,
                        'price_discount_trade_in' => 150000,
                        'price_discount_direct' => 0,
                    ],
                    'cars_count' => 3,
                    'seats' => 4,
                    'isImport' => false,
                    'transmission_type' => '',
                    'engine_url' => 'turbirovannyj',
                    'engine_volume' => '1.5',
                    'transmission' => 'Робот (AMT7)',
                    'engine_power' => '147',
                    'engine_type' => 'Турбо Бензин',
                    'drive' => 'Полный',
                    'transmission_short' => 'AMT7',
                    'url' => '#',
                    'engine_label' => '1.5 (147 л.с.) Турбо Бензин',
                    'seat_label' => '4 места',
                ],
                [
                    'id' => 7901,
                    'name' => 'Prime',
                    'full_name' => 'Prime/1.5 л. (147 л.с.)/Турбо Бензин/AMT6/Передний/2025/4 мест',
                    'year' => '2025',
                    'codes' => ['Prime 1.5T'],
                    'prices' => [
                        'price' => 2380000,
                        'price_min' => 1488000,
                        'price_text' => 'Цена по запросу',
                        'price_text_short' => 'По запросу',
                        'show_price' => 1,
                        'price_discount_max' => 892000,
                        'price_discount_credit' => 250000,
                        'price_discount_trade_in' => 150000,
                        'price_discount_direct' => 120000,
                    ],
                    'cars_count' => 33,
                    'seats' => 4,
                    'isImport' => false,
                    'transmission_type' => '',
                    'engine_url' => 'turbirovannyj',
                    'engine_volume' => '1.5',
                    'transmission' => 'Робот (AMT6)',
                    'engine_power' => '147',
                    'engine_type' => 'Турбо Бензин',
                    'drive' => 'Передний',
                    'transmission_short' => 'AMT6',
                    'url' => '#',
                    'engine_label' => '1.5 (147 л.с.) Турбо Бензин',
                    'seat_label' => '4 места',
                ],
                [
                    'id' => 7900,
                    'name' => 'Active',
                    'full_name' => 'Active/1.5 л. (147 л.с.)/Турбо Бензин/AMT6/Передний/2025/4 мест',
                    'year' => '2025',
                    'codes' => ['Active 1.5T'],
                    'prices' => [
                        'price' => 2250000,
                        'price_min' => 1384000,
                        'price_text' => 'Цена по запросу',
                        'price_text_short' => 'По запросу',
                        'show_price' => 1,
                        'price_discount_max' => 866000,
                        'price_discount_credit' => 250000,
                        'price_discount_trade_in' => 150000,
                        'price_discount_direct' => 120000,
                    ],
                    'cars_count' => 43,
                    'seats' => 4,
                    'isImport' => false,
                    'transmission_type' => '',
                    'engine_url' => 'turbirovannyj',
                    'engine_volume' => '1.5',
                    'transmission' => 'Робот (AMT6)',
                    'engine_power' => '147',
                    'engine_type' => 'Турбо Бензин',
                    'drive' => 'Передний',
                    'transmission_short' => 'AMT6',
                    'url' => '#',
                    'engine_label' => '1.5 (147 л.с.) Турбо Бензин',
                    'seat_label' => '4 места',
                ],
                [
                    'id' => 7920,
                    'name' => 'CVT Line',
                    'full_name' => 'CVT Line/1.5 л. (113 л.с.)/Бензин/CVT/Передний/2025/4 мест',
                    'year' => '2025',
                    'codes' => ['Line 1.5 CVT'],
                    'prices' => [
                        'price' => 2129000,
                        'price_min' => 1263200,
                        'price_text' => 'Цена по запросу',
                        'price_text_short' => 'По запросу',
                        'show_price' => 1,
                        'price_discount_max' => 865800,
                        'price_discount_credit' => 250000,
                        'price_discount_trade_in' => 150000,
                        'price_discount_direct' => 150000,
                    ],
                    'cars_count' => 7,
                    'seats' => 4,
                    'isImport' => false,
                    'transmission_type' => '',
                    'engine_url' => '',
                    'engine_volume' => '1.5',
                    'transmission' => 'Вариатор (CVT)',
                    'engine_power' => '113',
                    'engine_type' => 'Бензин',
                    'drive' => 'Передний',
                    'transmission_short' => 'CVT',
                    'url' => '#',
                    'engine_label' => '1.5 (113 л.с.) Бензин',
                    'seat_label' => '4 места',
                ],
                [
                    'id' => 7919,
                    'name' => 'MT Line',
                    'full_name' => 'MT Line/1.5 л. (113 л.с.)/Бензин/MT5/Передний/2025/4 мест',
                    'year' => '2025',
                    'codes' => ['Line 1.5 МT'],
                    'prices' => [
                        'price' => 1999000,
                        'price_min' => 1199200,
                        'price_text' => 'Цена по запросу',
                        'price_text_short' => 'По запросу',
                        'show_price' => 1,
                        'price_discount_max' => 799800,
                        'price_discount_credit' => 250000,
                        'price_discount_trade_in' => 150000,
                        'price_discount_direct' => 100000,
                    ],
                    'cars_count' => 8,
                    'seats' => 4,
                    'isImport' => false,
                    'transmission_type' => '',
                    'engine_url' => '',
                    'engine_volume' => '1.5',
                    'transmission' => 'Механика (MT5)',
                    'engine_power' => '113',
                    'engine_type' => 'Бензин',
                    'drive' => 'Передний',
                    'transmission_short' => 'MT5',
                    'url' => '#',
                    'engine_label' => '1.5 (113 л.с.) Бензин',
                    'seat_label' => '4 места',
                ],
            ],

            'options' => [
                'compare' => [
                    'Экстерьер' => [
                        '16-дюймовые алюминиевые литые диски' => [
                            7920 => true,
                            7919 => true,
                        ],
                        '17-дюймовые алюминиевые литые диски' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                        'Дефлекторы для 2-го ряда' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                            7920 => true,
                        ],
                        'Электропривод складывания зеркал' => [
                            8555 => true,
                            7901 => true,
                        ],
                    ],
                    'Интерьер' => [
                        'Передние и задние электростеклоподъемники с защитой от защемления' => [
                            8555 => true,
                            7901 => true,
                        ],
                        'Подсветка перчаточного ящика' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                    ],
                    'Безопасность' => [
                        'Боковые передние подушки безопасности' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                        'Камера заднего вида' => [
                            8553 => true,
                            7900 => true,
                            7920 => true,
                            7919 => true,
                        ],
                        'Передние датчики парковки' => [
                            8555 => true,
                            7901 => true,
                        ],
                        'Система кругового обзора 360*' => [
                            8555 => true,
                            7901 => true,
                        ],
                    ],
                    'Комфорт' => [
                        'Водительское сиденье с механической регулировкой в 6-ти направлениях' => [
                            8553 => true,
                            7900 => true,
                            7920 => true,
                            7919 => true,
                        ],
                        'Водительское сиденье с электрической регулировкой в 6-ти направлениях' => [
                            8555 => true,
                            7901 => true,
                        ],
                        'Выбор режима вождения' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                        'Климат-контроль, 2 зоны' => [
                            8555 => true,
                            7901 => true,
                        ],
                        'Обогрев передних сидений' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                        'Обогрев передних сидений (без спинки)' => [
                            7920 => true,
                            7919 => true,
                        ],
                        'Обогрев сидений 2-го ряда (без спинки)' => [
                            8555 => true,
                            7901 => true,
                        ],
                        'Электрический кондиционер' => [
                            8553 => true,
                            7900 => true,
                            7920 => true,
                            7919 => true,
                        ],
                    ],
                    'Аудио' => [
                        '4 динамика' => [
                            8553 => true,
                            7900 => true,
                            7920 => true,
                            7919 => true,
                        ],
                        '6 динамиков' => [
                            8555 => true,
                            7901 => true,
                        ],
                        'USB-разъем сзади' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                        'Голосовое управление' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                        'Сдвоенные экраны 2х10.25"' => [
                            8555 => true,
                            8553 => true,
                            7901 => true,
                            7900 => true,
                        ],
                        'Экран борткомпьютера 3.5"' => [
                            7920 => true,
                            7919 => true,
                        ],
                        'Экран мультимедиа 10.25"' => [
                            7920 => true,
                            7919 => true,
                        ],
                    ],
                    'Опции' => [],
                ],
                'base' => [
                    'Экстерьер' => [
                        'Рейлинги на крыше',
                        'Светодиодные задние фонари',
                        'Задний спортивный спойлер',
                        'Боковые зеркала с электрической регулировкой, обогревом, повторителями поворотов',
                        'Светодиодные фары основного света',
                        'Передние дневные светодиодные ходовые огни',
                        'Окраска металлик',
                    ],
                    'Безопасность' => [
                        'Задние датчики парковки',
                        'Эра Глонасс',
                        'Система стабилизации курсовой устойчивости (ESС)',
                        'Антиблокировочная тормозная система (ABS)',
                        'Задний стеклоочиститель',
                        'Датчик превышения заданной скорости',
                        'Подушки безопасности водителя и переднего пассажира',
                        'Уменьшенное запасное колесо',
                        'Передние ремни безопасности с регулировкой по высоте',
                        'Система мониторинга давления и температуры в шинах (TMPS)',
                        'Функция отсрочки выключения фар (Follow me home)',
                        'Иммобилайзер',
                        'Автоматическое запирание дверей на скорости',
                        'Блокировка замков задних дверей от открывания детьми механическая',
                        'Система удержания детских кресел Isofix для 2-го ряда',
                        'Функция авто включения фар при вождении в темное время (датчик света)',
                    ],
                    'Комфорт' => [
                        'Круиз-контроль',
                        'Обогрев лобового стекла',
                        'Обогрев форсунок стеклоомывателя',
                        'Центральный замок с дистанционным управлением',
                        'Электрический стояночный тормоз с функцией AutoHold',
                        'Обогрев рулевого колеса',
                        'Электрический усилитель рулевого управления',
                        'Дистанционный запуск двигателя и прогрева салона',
                        'Рулевая колонка с регулировкой в 4-х направлениях',
                        'Складная спинка сидений 2-го ряда в соотношении 1\3-2\3',
                        'Пассажирское сиденье с механической регулировкой в 4-х направлениях',
                        'Запуск двигателя кнопкой (ключ в кармане)',
                        'Дистанционное управление открытием замка двери багажника',
                    ],
                    'Аудио' => [
                        'Система "Свободные руки"(Hands free) с Bluetooth-связью с мобильным телефоном',
                        'Радио',
                        'Телематика',
                        '2 USB-разъема спереди',
                        'Apple Car Play \ Android Auto',
                    ],
                    'Интерьер' => [
                        'Центральный подлокотник для 2-го ряда сидений',
                        'Ручки для пассажиров с микролифтом',
                        'Сиденья с отделкой из эко-кожи',
                        'Передние и задние электростеклоподъемники',
                        'Передний центральный подлокотник',
                        'Подголовники всех сидений',
                        'Зеркало в солнцезащитном козырьке водителя и пассажира',
                        'Очечник',
                    ],
                ],
            ],
        ]);
    }
}
